config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update]
  resources :books
  root 'home#top'
  get 'home/about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books, dependent: :destroy
  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
validates :name, presence: true
validates :name,length: { minimum: 2, maximum: 20 }
validates :introduction,length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	#デバイス機能実行前にconfigure_permitted_parametersの実行をする。
	protect_from_forgery with: :exception
  before_action :set_current_user
  protected

  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  def after_sign_up_path_for(resource)
     user_path(resource)
  end

  def after_sign_in_path_for(resource)
     user_path(resource)
  end

  def after_sign_out_path_for(resource)
     root_path
  end


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    #sign_upの際にnameのデータ操作を許。追加したカラム。
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!
    before_action :ensure_correct_user, {only: [:edit, :update, :destroy]}
  def show
  	@books = Book.find(params[:id])
    @user = @books.user
    @book = Book.new
  end

  def index
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @book = Book.new
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id = current_user.id
  	if@book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
    @book.user_id = current_user.id
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

    def set_book
      @book = Book.find(params[:id])
    end

  def book_params
  	params.require(:book).permit(:title, :body,)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
     if @book.user != current_user
      flash[:notice] = "権限がありません"
      redirect_to(books_path)
    end
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:top, :about]
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
	before_action :baria_user, only: [:update, :edit]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(current_user), notice: "successfully updated user!"
  	else
  		render :edit
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_newform.html.erb
<%= form_for(@book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :Opinion %>
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit "追加",class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="er">
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% end %>
</div>

<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="er">
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% end %>
</div>

<div class="container">
  <div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

		<!--books一覧 -->
	<div class="col-xs-9">
		<h2>Books index</h2>
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
		<!--books一覧 -->
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
			<tbody>
				<tr>
					<td>
						<%= link_to (@books.user) do %>
						<%= attachment_image_tag(@books.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @user.name %>
						<% end %>
					</td>
					<td><%= link_to @books.title, @books %></td>
					<td><%= @books.body %></td>

					<% if @user.id == current_user.id %>
					<td><%= link_to "Edit",edit_book_path(@books), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy",@books, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
				</tr>
					<% end %>
			</tbody>
		</table>

	</div>
  </div>
</div>

app/views/home/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h1>

app/views/home/top.html.erb
<div class="row">
	<div class="main col-md-offset-3 col-md-6">
		<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>


		<% if user_signed_in? %>
			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", user_path(current_user), class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign up", user_path(current_user), class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>

		<% else %>
			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				<% end %>
				</div>
			</div>

	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ヘッダーの記述-->
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <!--if文でサインインとアウト時の表示を変更-->
            <% if user_signed_in? %>
            <li><%= link_to ' home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' users', users_path, class: 'glyphicon glyphicon-user users' %></li>
            <li><%= link_to ' books', books_path, class: 'glyphicon glyphicon-book books' %></li>
            <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
            <li><%= link_to ' home', root_path, class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' about', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
            <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
            <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>
    <!--ヘッダーの記述-->
    <div class="container">

      <p id="notice"><%= notice %></p> <!--デバイスでnotice設定されているので呼び出してるだけ-->

    </div>


<footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

  </body>
   <%= yield %>

</html>

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
</table>

<div class="row">
	    <% if user.id == current_user.id %>
    <%= link_to("", "/users/#{user.id}/edit", { class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench"}) %>

    <% else %>

    <%= link_to user_path(current_user.id), class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench' do %>
    <% end %>
    <% end %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<div class="er">
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
</div>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
	<div class="col-xs-3">

<h2>User info</h2>
<%= render 'users/profile', user: current_user %>
<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

<h2>New book</h2>
<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
<h2>Users</h2>
<!--users一覧 -->
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name%></td>
			<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
		</tr>
		<% end %>
	</tbody>
</table>
	</div>
<!--users一覧 -->

  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
	<div class="col-xs-3">

<h2>User info</h2>
<%= render 'users/profile', user: @user %>
<!--同コントローラーのviewで表示ならusersは省略可 -->

<h2>New book</h2>
<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">
<h2>Books</h2>
<!--books一覧 -->
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @books.each do |book| %>
		<tr>
			<td>
				<%= link_to (book.user) do %>
				<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
				<% end %>
			</td>
			<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
			<td><%= book.body %></td>
		</tr>
		<% end %>
	</tbody>
</table>
	</div>
<!--books一覧 -->

  </div>
</div>